In [8]:
import datetime
import random
import altair as alt
import numpy as np
import pandas as pd
import streamlit as st

In [12]:
df2 = pd.read_csv("ventas_df.csv", sep=";")

/tmp/ipykernel_14967/363889082.py:1: DtypeWarning: Columns (0: Unnamed: 2, 1: Unnamed: 3, 2: Unnamed: 4, 3: Unnamed: 8, 4: Unnamed: 9, 5: Unnamed: 10, 6: Unnamed: 11, 7: Unnamed: 13) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("ventas_df.csv", sep=";")

In [13]:
df2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ID unico de factura,fecha,dia,mes,año,colegio,articulo,talla,hombro,talle,...,largo,ID unico de artículo,cantidad,precio individual,subtotal,Estado Factura,Producto pendiente por entregar,Clasificación_antiguo,Método de pago_antiguo,Nombre
2,NA FACTURA-44572-liceo pupo jimenez_falda_8,"martes, 11 de enero de 2022",11,1,2022,liceo pupo jimenez,falda,8,NaN,NaN,...,NaN,liceo pupo jimenez_falda_8,1,70.000,70.000,PAGADA / CERRADA,NO,VENTA,ef,NA
3,NA FACTURA-44572-liceo pupo jimenez_camiseta f...,"martes, 11 de enero de 2022",11,1,2022,liceo pupo jimenez,camiseta fisica,8,NaN,NaN,...,NaN,liceo pupo jimenez_camiseta fisica_8,1,31.000,31.000,PAGADA / CERRADA,NO,VENTA,ef,NA
4,NA FACTURA-44572-liceo pupo jimenez_bombacho_6,"martes, 11 de enero de 2022",11,1,2022,liceo pupo jimenez,bombacho,6,NaN,NaN,...,NaN,liceo pupo jimenez_bombacho_6,1,34.000,34.000,PAGADA / CERRADA,NO,VENTA,ef,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45934,BGT_CLE_46175---,"martes, 2 de junio de 2026",2,6,2026,Antonio Narino,Camiseta diario/fisica,10,NaN,NaN,...,NaN,Antonio Narino_Camiseta diario/fisica_10,2,45.000,90.000,PAGADA / CERRADA,NO,VENTA,NaN,-
45935,BGT_CLE_46175---,"martes, 2 de junio de 2026",2,6,2026,la inmaculada,bombacho,10,NaN,NaN,...,NaN,la inmaculada_bombacho_10,1,58.000,58.000,PAGADA / CERRADA,NO,VENTA,NaN,-
45936,BGT_CLE_46175---,"martes, 2 de junio de 2026",2,6,2026,la inmaculada,camiseta fisica,10,NaN,NaN,...,NaN,la inmaculada_camiseta fisica_10,1,41.000,41.000,PAGADA / CERRADA,NO,VENTA,NaN,-
45937,BGT_CLE_46176---,"miércoles, 3 de junio de 2026",3,6,2026,gimnasio vallegrande,camiseta de fisica externa,M,NaN,NaN,...,NaN,gimnasio vallegrande_camiseta de fisica externa_M,1,53.000,53.000,PAGADA / CERRADA,NO,VENTA,NaN,-
45938,BGT_CLE_46176---,"miércoles, 3 de junio de 2026",3,6,2026,gimnasio vallegrande,camiseta de diario,S,NaN,NaN,...,NaN,gimnasio vallegrande_camiseta de diario_S,1,59.000,59.000,PAGADA / CERRADA,NO,VENTA,NaN,-

In [15]:
df=df2.copy()
    # La fila 1 contiene los nombres reales
df.columns = df.iloc[1]

    # Eliminar fila vacía y fila de encabezados
df = df.iloc[2:].reset_index(drop=True)

st.session_state.df = df

2026-06-03 16:13:28.408 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-03 16:13:28.410 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2026-06-03 16:13:28.410 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [16]:
df

1,ID unico de factura,fecha,dia,mes,año,colegio,articulo,talla,hombro,talle,...,largo,ID unico de artículo,cantidad,precio individual,subtotal,Estado Factura,Producto pendiente por entregar,Clasificación_antiguo,Método de pago_antiguo,Nombre
0,NA FACTURA-44572-liceo pupo jimenez_falda_8,"martes, 11 de enero de 2022",11,1,2022,liceo pupo jimenez,falda,8,NaN,NaN,...,NaN,liceo pupo jimenez_falda_8,1,70.000,70.000,PAGADA / CERRADA,NO,VENTA,ef,NA
1,NA FACTURA-44572-liceo pupo jimenez_camiseta f...,"martes, 11 de enero de 2022",11,1,2022,liceo pupo jimenez,camiseta fisica,8,NaN,NaN,...,NaN,liceo pupo jimenez_camiseta fisica_8,1,31.000,31.000,PAGADA / CERRADA,NO,VENTA,ef,NA
2,NA FACTURA-44572-liceo pupo jimenez_bombacho_6,"martes, 11 de enero de 2022",11,1,2022,liceo pupo jimenez,bombacho,6,NaN,NaN,...,NaN,liceo pupo jimenez_bombacho_6,1,34.000,34.000,PAGADA / CERRADA,NO,VENTA,ef,NA
3,NA FACTURA-44572-liceo pupo jimenez_falda_6,"martes, 11 de enero de 2022",11,1,2022,liceo pupo jimenez,falda,6,NaN,NaN,...,NaN,liceo pupo jimenez_falda_6,1,70.000,70.000,PAGADA / CERRADA,NO,VENTA,ta,NA
4,NA FACTURA-44572-liceo pupo jimenez_blusa_6,"martes, 11 de enero de 2022",11,1,2022,liceo pupo jimenez,blusa,6,NaN,NaN,...,NaN,liceo pupo jimenez_blusa_6,2,27.000,54.000,PAGADA / CERRADA,NO,VENTA,ta,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45932,BGT_CLE_46175---,"martes, 2 de junio de 2026",2,6,2026,Antonio Narino,Camiseta diario/fisica,10,NaN,NaN,...,NaN,Antonio Narino_Camiseta diario/fisica_10,2,45.000,90.000,PAGADA / CERRADA,NO,VENTA,NaN,-
45933,BGT_CLE_46175---,"martes, 2 de junio de 2026",2,6,2026,la inmaculada,bombacho,10,NaN,NaN,...,NaN,la inmaculada_bombacho_10,1,58.000,58.000,PAGADA / CERRADA,NO,VENTA,NaN,-
45934,BGT_CLE_46175---,"martes, 2 de junio de 2026",2,6,2026,la inmaculada,camiseta fisica,10,NaN,NaN,...,NaN,la inmaculada_camiseta fisica_10,1,41.000,41.000,PAGADA / CERRADA,NO,VENTA,NaN,-
45935,BGT_CLE_46176---,"miércoles, 3 de junio de 2026",3,6,2026,gimnasio vallegrande,camiseta de fisica externa,M,NaN,NaN,...,NaN,gimnasio vallegrande_camiseta de fisica externa_M,1,53.000,53.000,PAGADA / CERRADA,NO,VENTA,NaN,-
45936,BGT_CLE_46176---,"miércoles, 3 de junio de 2026",3,6,2026,gimnasio vallegrande,camiseta de diario,S,NaN,NaN,...,NaN,gimnasio vallegrande_camiseta de diario_S,1,59.000,59.000,PAGADA / CERRADA,NO,VENTA,NaN,-